language: python
matrix:
  include:
  - name: "Older Python"
    python:
      - "2.7"
      - "3.2"
      - "3.3"
      - "3.4"
    env: TEST_SUITE=suite_3_5_unit
  - name: "Newer Python"
    dist: xenial
    sudo: true
    python:
      - "3.5"
      - "3.6"
      - "3.7"
script: python setup.py test
